### ISSUE TITLE
Bug when trying to create FastApiRedisCache() object

### ISSUE THREAD

**Issue by carc-taylor** [seapagan/fastapi-redis-cache-reborn#94]
Error originates from this line:

https://github.com/seapagan/fastapi-redis-cache-reborn/blob/b7b7dc8414262a338ce9df629c8a78630e35649f/fastapi_redis_cache/client.py#L264

`zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key localtime'`

**Comment by seapagan** [comment]
@carc-taylor thanks for the report. I can't duplicate the error on my system or the tests. I think that function is from the original project I forked, and from a bit of checking the `ZoneInfo("localtime")` may not be a valid identifier for the local timezone on all systems. I'll rewrite it using `tzlocal` or similar.

To help, can you give me the below information please?
- your operating system and version
- version of Python you are using with this library.

Thanks in advance!

**Comment by seapagan** [comment]
@carc-taylor I've opened a PR #100 that will hopefully fix it. Can you install the cache locally from that branch and try it on your system please?

**Comment by carc-taylor** [comment]
@seapagan Looks like that fixes it!

For reference I'm using Python 3.10.12, and macOS Ventura 13.3.1 (M1 Chip)

**Comment by seapagan** [comment]
@carc-taylor excellent, thanks for the report. I'll put out a new release shortly :+1:

**Comment by seapagan** [comment]
version 0.3.1 has been released with this fix.
